### ISSUE TITLE
Calling TestOutputLogger.BeginScope(...) with state with circular reference causes exception 

### ISSUE THREAD

**Issue by webseb** [Divergic/Divergic.Logging.Xunit#6]
This is the test to reproduce the error:

```csharp
[Fact]
public void Should_Not_Throw()
{
    var sut = this.output.BuildLogger();
    var state = new CircularReference();
    state.Self = state;
    using (sut.BeginScope(state))
    {
        sut.LogDebug("...");
    }
}
private class CircularReference
{
    public CircularReference Self { get; set; }
}
```

It's a "feature" of Newtonsoft.Json
https://www.newtonsoft.com/json/help/html/ReferenceLoopHandlingIgnore.htm
https://stackoverflow.com/questions/13510204/json-net-self-referencing-loop-detected

The bug can be fixed by adding the appropriate JsonSerializerSettings to the call to JsonConvert.SerializeObject(...)

```csharp
string actual = JsonConvert.SerializeObject(state, new JsonSerializerSettings
{
    ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
});
```

**Comment by roryprimrose** [comment]
Thanks for the report. Can you please verify it is fixed via the beta package at https://www.nuget.org/packages/Divergic.Logging.Xunit/2.0.1-beta0001

**Comment by webseb** [comment]
The fix exchanges the JsonSerializationException with an OutOfMemoryException.

```csharp
System.AggregateException : An error occurred while writing to logger(s). (Exception of type 'System.OutOfMemoryException' was thrown.)
---- System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
   at Microsoft.Extensions.Logging.Logger.BeginScope[TState](TState state)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.SingleOrDefaultAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at

[...]

----- Inner Stack Trace -----
   at System.Text.StringBuilder.ToString()
   at Divergic.Logging.Xunit.ScopeWriter.DetermineScopeStateMessage() in D:\a\1\s\Divergic.Logging.Xunit\ScopeWriter.cs:line 94
   at Divergic.Logging.Xunit.ScopeWriter..ctor(ITestOutputHelper outputHelper, Object state, Int32 depth, Action onScopeEnd) in D:\a\1\s\Divergic.Logging.Xunit\ScopeWriter.cs:line 24
   at Divergic.Logging.Xunit.TestOutputLogger.BeginScope[TState](TState state) in D:\a\1\s\Divergic.Logging.Xunit\TestOutputLogger.cs:line 45
   at Microsoft.Extensions.Logging.Logger.BeginScope[TState](TState state)
```

**Comment by roryprimrose** [comment]
Hmm, I'm confused by this one. There is no StringBuilder in ScopeWriter. If it was part of Newtonsoft.Json then I would expect to see that in the stack trace. Not sure I can do anything about this without more information. Any ideas?

**Comment by roryprimrose** [comment]
There is a StringBuilder involved in Newtonsoft.Json. Can you try running ```JsonConvert.SerializeObject(_state, SerializerSettings.Default);``` directly on your object instead of pushing it to the logger?

**Comment by webseb** [comment]
The offending code is from Entity Framework Core

```csharp
public abstract class Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor
{
    // line 184
    public virtual Func<QueryContext, IAsyncEnumerable<TResult>> CreateAsyncQueryExecutor<TResult>(
QueryModel queryModel)
    {
      using (this.QueryCompilationContext.Logger.Logger.BeginScope<EntityQueryModelVisitor>(this))
      {
        [...]
      }
    }
}
```
I'm still investigating what exactly causes the `OutOfMemoryException`.

**Comment by webseb** [comment]
Sorry it took me so long to come back to this issue. I couldn't find the reason but I did find a workaround for the problem.

If you add a custom JsonConverter to `SerializerSettings.Default.Converters` you can write an arbitrary message into the json representing the `EntityQueryModelVisitor`

e.g.
````csharp
internal class EntityQueryModelVisitorJsonConverter : JsonConverter<EntityQueryModelVisitor>
{
    public override void WriteJson(JsonWriter writer, EntityQueryModelVisitor value, JsonSerializer serializer)
    {
        writer.WriteStartObject();

        writer.WritePropertyName("Error");

        writer.WriteValue("Can't serialize objects derived from 'Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor'.");

        writer.WriteEndObject();
    }

    public override EntityQueryModelVisitor ReadJson(
        JsonReader reader,
        Type objectType,
        EntityQueryModelVisitor existingValue,
        bool hasExistingValue,
        JsonSerializer serializer)
    {
        // We don't want so de-serialize it
        throw new NotImplementedException();
    }
}
````
